# Generated by Django 5.2.1 on 2025-08-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0007_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
    ]
