# Generated by Django 5.2.1 on 2025-08-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0008_auto_20250824_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Image',
            field=models.ImageField(blank=True, default='picture/default.jpg', null=True, upload_to='picture'),
        ),
    ]
