# Generated by Django 5.2.1 on 2025-08-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0009_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gate_fees',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='gate_fees2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
