# Generated by Django 5.2.1 on 2025-08-24 22:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0010_event_gate_fees_event_gate_fees2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='registration',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='ticket_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP')], default='regular', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('event', 'user', 'ticket_type')},
        ),
    ]
