# Generated by Django 5.2.1 on 2025-08-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0011_alter_registration_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='picture'),
        ),
    ]
