# Generated by Django 5.2.1 on 2025-08-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0012_alter_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Image',
            new_name='image',
        ),
    ]
